# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.20.1,1.21)
# The Forge version must agree with the Minecraft version to get a valid artifact
forge_version=47.4.20
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[47,)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[47,)
# The mapping channel to use for mappings.
# The default set of supported mapping channels are ["official", "snapshot", "snapshot_nodoc", "stable", "stable_nodoc"].
# Additional mapping channels can be registered through the "channelProviders" extension in a Gradle plugin.
#
# | Channel   | Version              |                                                                                |
# |-----------|----------------------|--------------------------------------------------------------------------------|
# | official  | MCVersion            | Official field/method names from Mojang mapping files                          |
# | parchment | YYYY.MM.DD-MCVersion | Open community-sourced parameter names and javadocs layered on top of official |
#
# You must be aware of the Mojang license when using the 'official' or 'parchment' mappings.
# See more information here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md
#
# Parchment is an unofficial project maintained by ParchmentMC, separate from Minecraft Forge.
# Additional setup is needed to use their mappings, see https://parchmentmc.org/docs/getting-started
mapping_channel=official
# The mapping version to query from the mapping channel.
# This must match the format required by the mapping channel.
mapping_version=1.20.1


## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=gtominifix
# The human-readable display name for the mod.
mod_name=GTO \u8ff7\u4f60\u4fee\u590d
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.0.4
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.lai.gtominifix
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=LAI
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=\u4fee\u590d GTO \u65c5\u884c\u624b\u6756\u5411\u4e0b\u77ac\u79fb\u65f6\u843d\u70b9\u5361\u8fdb\u65b9\u5757\u5bfc\u81f4\u7a92\u606f\u6389\u8840\u7684\u95ee\u9898\uff1b\u4fee\u590d GTO \u677f\u6761\u7bb1\uff08LDLib ModularUI \u754c\u9762\uff09\u65e0\u6cd5\u4f7f\u7528\u5bb9\u5668\u6279\u91cf\u8f6c\u79fb\u5feb\u6377\u952e\u7684\u95ee\u9898\uff1aCtrl+Shift+\u5de6\u952e\u628a\u540c\u7c7b\u7269\u54c1\u5168\u90e8\u8f6c\u79fb\u3001\u7a7a\u683c+\u5de6\u952e\u628a\u80cc\u5305 27 \u683c\u5168\u90e8\u8f6c\u79fb\uff1b\u4e3a Functional Storage \u7684\u4e00\u683c/\u4e24\u683c/\u56db\u683c\u62bd\u5c49\u8865\u4e0a Ctrl+Shift+\u5de6\u952e = \u5c3d\u91cf\u586b\u6ee1\u73a9\u5bb6\u80cc\u5305\u3002
